# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-04 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170630_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='emai',
            new_name='email',
        ),
    ]
